from enum import Enum

class Ability(Enum):
    HUGE_POWER = "Huge Power"
    PURE_POWER = "Pure Power"
    REGENERATOR = "Regenerator"
    NATURAL_CURE = "Natural Cure"
    SAND_RUSH = "Sand Rush"
    POISON_HEAL = "Poison Heal"
    LEVITATE = "Levitate"
    MAGIC_GUARD = "Magic Guard"
    DROUGHT = "Drought"
    DRIZZLE = "Drizzle"
    SAND_STREAM = "Sand Stream"
    SNOW_WARNING = "Snow Warning"
    ICE_BODY = "Ice Body"
    VOLT_ABSORB = "Volt Absorb"
    WATER_ABSORB = "Water Absorb"
    JUSTIFIED = "Justified"
    SCRAPPY = "Scrappy"
    RAIN_DISH = "Rain Dish"
    HYDRATION = "Hydration"
    MAGNET_PULL = "Magnet Pull"
    TECHNICIAN = "Technician"
    CONTRARY = "Contrary"
    SWIFT_SWIM = "Swift Swim"
    GRASSY_SURGE = "Grassy Surge"
    MISTY_SURGE = "Misty Surge"
    PSYCHIC_SURGE = "Psychic Surge"
    ELECTRIC_SURGE = "Electric Surge"
    NO_GUARD = "No Guard"
    VICTORY_STAR = "Victory Star"

    FLASH_FIRE = "Flash Fire"
    SAND_FORCE = "Sand Force"
    STATIC = "Static"
    FLAME_BODY = "Flame Body"
    STURDY = "Sturdy"
    NONE = "None"
    # ...
