from enum import Enum


class Ability(Enum):
    HUGE_POWER = "Huge Power"
    PURE_POWER = "Pure Power"
    REGENERATOR = "Regenerator"
    NATURAL_CURE = "Natural Cure"
    SAND_RUSH = "Sand Rush"
    POISON_HEAL = "Poison Heal"
    LEVITATE = "Levitate"
    MAGIC_GUARD = "Magic Guard"
    DROUGHT = "Drought"
    DRIZZLE = "Drizzle"
    SAND_STREAM = "Sand Stream"
    SNOW_WARNING = "Snow Warning"
    ICE_BODY = "Ice Body"
    VOLT_ABSORB = "Volt Absorb"
    WATER_ABSORB = "Water Absorb"
    JUSTIFIED = "Justified"
    SCRAPPY = "Scrappy"
    RAIN_DISH = "Rain Dish"
    HYDRATION = "Hydration"
    MAGNET_PULL = "Magnet Pull"
    TECHNICIAN = "Technician"
    CONTRARY = "Contrary"
    SWIFT_SWIM = "Swift Swim"
    GRASSY_SURGE = "Grassy Surge"
    MISTY_SURGE = "Misty Surge"
    PSYCHIC_SURGE = "Psychic Surge"
    ELECTRIC_SURGE = "Electric Surge"
    NO_GUARD = "No Guard"
    VICTORY_STAR = "Victory Star"
    THICK_FAT = "Thick Fat"
    SAP_SIPPER = "Sap Sipper"
    TRACE = "Trace"
    SAND_FORCE = "Sand Force"
    TOUGH_CLAWS = "Tough Claws"
    ROUGH_SKIN = "Rough Skin"
    IRON_BARBS = "Iron Barbs"
    STORM_DRAIN = "Storm Drain"
    FLASH_FIRE = "Flash Fire"
    STATIC = "Static"
    FLAME_BODY = "Flame Body"
    BEAST_BOOST = "Beast Boost"
    STURDY = "Sturdy"
    MAGIC_BOUNCE = "Magic Bounce"
    MOLD_BREAKER = "Mold Breaker"
    TORRENT = "Torrent"
    SWARM = "Swarm"
    BLAZE = "Blaze"
    OVERGROW = "Overgrow"
    PRESSURE = "Pressure"
    PROTEAN = "Protean"
    BATTLE_BOND = "Battle Bond"
    SERENE_GRACE = "Serene Grace"
    TERA_VOLTAGE = "Teravolt"
    INTIMIDATE = "Intimidate"
    SOUL_HEART = "Soul-Heart"
    BULLET_PROOF = "Bulletproof"
    SOUNDPROOF = "Soundproof"

    # PAS ENCORE FAITS CEUX LA
    UNBURDEN = "Unburden"
    UNAWARE = "Unaware"
    OVERCOAT = "Overcoat"







    NONE = "None"
    # ...
