from enum import Enum


class Item(Enum):
    # Items
    LEFTOVERS = "Leftovers"
    CHOICE_BAND = "Choice Band"
    CHOICE_SPECS = "Choice Specs"
    CHOICE_SCARF = "Choice Scarf"
    FOCUS_SASH = "Focus Sash"
    TOXIC_ORB = "Toxic Orb"
    GRASSY_SEED = "Grassy Seed"
    PSYCHIC_SEED = "Psychic Seed"
    ELECTRIC_SEED = "Electric Seed"
    MISTY_SEED = "Misty Seed"
    DAMP_ROCK = "Damp Rock"
    HOT_ROCK = "Hot Rock"
    ICY_ROCK = "Icy Rock"
    SMOOTH_ROCK = "Smooth Rock"
    BLACK_SLUDGE = "Black Sludge"
    FLAME_ORB = "Flame Orb"

    # Mega Stones
    ALAKAZAMITE = "Alakazamite"
    BEEDRILLITE = "Beedrillite"
    BLAZIKENITE = "Blazikenite"
    CHARMINITE = "Charminite"
    CHARIZARDITE_X = " Charizardite X"
    CHARIZARDITE_Y = "Chrizardite Y"
    DIANCITE = "Diancite"
    GARCHOMPITE = "Garchompite"
    LOPUNNITE = "Lopunnite"
    MANECTITE = "Manectite"
    MAWILITE = "Mawilite"
    METAGROSSITE = "Metagrossite"
    PIDGEOTITE = "Pidgeotite"
    PINSIRITE = "Pinsirite"
    SALAMENCITE = "Salamencite"
    SCIZORITE = "Scizorite"
    TYRANITARITE = "Tyranitarite"
    SWAMPERTITE = "Swampertite"
    VENUSAURITE = "Venusaurite"

    # Z-Crystals
    NORMALIUM_Z = "Normalium Z"
    FIGHTINIUM_Z = "Fightinium Z"
    FLYINIUM_Z = "Flyinium Z"
    POISONIUM_Z = "Poisonium Z"
    GROUNDIUM_Z = "Groundium Z"
    ROCKIUM_Z = "Rockium Z"
    BUGINIUM_Z = "Buginium Z"
    GHOSTIUM_Z = "Ghostium Z"
    STEELIUM_Z = "Steelium Z"
    FIRIUM_Z = "Firium Z"
    WATERIUM_Z = "Waterium Z"
    GRASSIUM_Z = "Grassium Z"
    ELECTRIUM_Z = "Electrium Z"
    PSYCHIUM_Z = "Psychium Z"
    ICINIUM_Z = "Icium Z"
    DRAGONIUM_Z = "Dragonium Z"
    DARKINIUM_Z = "Darkinium Z"
    FAIRIUM_Z = "Fairium Z"
    INACTIVE_Z_CRYSTAL = "Inactive Z-Crystal"

    # TODO

    NONE = "None"
