from MoveConsole import *

FLAMETHROWER = Move("Flamethrower", Type.FIRE, MoveCategory.SPECIAL, 90, 100, 15, SecondaryEffects.COMMON_BURN, "pokemon")
EARTHQUAKE = Move("Earthquake", Type.GROUND, MoveCategory.PHYSICAL, 100, 100, 10, SecondaryEffects.NONE, "pokemon")
ICEBEAM = Move("Ice Beam", Type.ICE, MoveCategory.SPECIAL, 90, 100, 10, SecondaryEffects.RARE_FREEZE, "pokemon")
WATER_SHURIKEN = Move("Water Shuriken", Type.WATER, MoveCategory.SPECIAL, 15, 100, 20, SecondaryEffects.NONE, "pokemon", priority=1)
HYDRO_PUMP = Move("Hydro Pump", Type.WATER, MoveCategory.SPECIAL, 110, 80, 5, SecondaryEffects.NONE, "pokemon")
THUNDERBOLT = Move("Thunderbolt", Type.ELECTRIC, MoveCategory.SPECIAL, 90, 100, 15, SecondaryEffects.RARE_PARALYSIS, "pokemon")
THUNDER = Move("Thunder", Type.ELECTRIC, MoveCategory.SPECIAL, 110, 70, 10, SecondaryEffects.COMMON_PARALYSIS, "pokemon")
SURF = Move("Surf", Type.WATER, MoveCategory.SPECIAL, 90, 100, 15, SecondaryEffects.NONE, "pokemon")
PSYCHIC = Move("Psychic", Type.PSYCHIC, MoveCategory.SPECIAL, 90, 100, 10, SecondaryEffects.RARE_SPECIAL_DEFENSE_DOWN, "pokemon")
PSYSHOK = Move("Psyshok", Type.PSYCHIC, MoveCategory.SPECIAL, 80, 100, 10, SecondaryEffects.NONE, "pokemon")
AQUA_JET = Move("Aqua Jet", Type.WATER, MoveCategory.PHYSICAL, 40, 100, 20, SecondaryEffects.NONE, "pokemon", priority=1)
AIR_SLASH = Move("Air Slash", Type.FLYING, MoveCategory.SPECIAL, 75, 95, 15, SecondaryEffects.RARE_FLINCH, "pokemon")
HEAVY_SLAM = Move("Heavy Slam", Type.STEEL, MoveCategory.PHYSICAL, 80, 100, 10, SecondaryEffects.NONE, "pokemon")
BULLET_PUNCH = Move("Bullet Punch", Type.STEEL, MoveCategory.PHYSICAL, 40, 100, 30, SecondaryEffects.NONE, "pokemon", priority=1)
CLOSE_COMBAT = Move("Close Combat", Type.FIGHT, MoveCategory.PHYSICAL, 120, 100, 5, SecondaryEffects.NONE, "pokemon")
PROTECT = Move("Protect", Type.NORMAL, MoveCategory.STATUS, 0, 100, 10, SecondaryEffects.PROTECT, "pokemon", priority=4)
LIGHT_SCREEN = Move("Light Screen", Type.PSYCHIC, MoveCategory.STATUS, 0, 100, 5, SecondaryEffects.LIGHT_SCREEN, "pokemon")
REFLECT = Move("Reflect", Type.PSYCHIC, MoveCategory.STATUS, 0, 100, 5, SecondaryEffects.REFLECT, "pokemon")
SPIKES = Move("Spikes", Type.GROUND, MoveCategory.STATUS, 0, 100, 20, SecondaryEffects.SPIKES, "player")
STEALTH_ROCK = Move("Stealth Rock", Type.ROCK, MoveCategory.STATUS, 0, 100, 20, SecondaryEffects.STEALTH_ROCK, "player")
TOXIC_SPIKES = Move("Toxic Spikes", Type.POISON, MoveCategory.STATUS, 0, 100, 20, SecondaryEffects.TOXIC_SPIKES, "player")
LEAF_STORM = Move("Leaf Storm", Type.GRASS, MoveCategory.SPECIAL, 130, 90, 5, SecondaryEffects.LOWER_SPE_ATK_BY_2, "pokemon")
LEECH_SEED = Move("Leech Seed", Type.GRASS, MoveCategory.STATUS, 0, 90, 10, SecondaryEffects.LEECH_SEED, "pokemon")
DRAGON_CLAW = Move("Dragon Claw", Type.DRAGON, MoveCategory.PHYSICAL, 80, 100, 15, SecondaryEffects.NONE, "pokemon")
DRAGON_DANCE = Move("Dragon Dance", Type.DRAGON, MoveCategory.STATUS, 0, 100, 20, SecondaryEffects.DRAGON_DANCE, "pokemon")
FIRE_BLAST = Move("Fire Blast", Type.FIRE, MoveCategory.SPECIAL, 110, 85, 5, SecondaryEffects.RARE_BURN, "pokemon")
MOONBLAST = Move("Moonblast", Type.FAIRY, MoveCategory.SPECIAL, 95, 100, 15, SecondaryEffects.RARE_SPECIAL_ATTACK_DOWN, "pokemon", bullet_move=True)
DIAMOND_STORM = Move("Diamond Storm", Type.ROCK, MoveCategory.PHYSICAL, 100, 95, 5, SecondaryEffects.DIAMOND_STORM, "pokemon")
EARTH_POWER = Move("Earth Power", Type.GROUND, MoveCategory.SPECIAL, 90, 100, 10, SecondaryEffects.RARE_SPECIAL_DEFENSE_DOWN, "pokemon")
SOFT_BOILED = Move("Soft Boiled", Type.NORMAL, MoveCategory.STATUS, 0, 100, 5, SecondaryEffects.SOFT_BOILED, "pokemon")
DARK_PULSE = Move("Dark Pulse", Type.DARK, MoveCategory.SPECIAL, 80, 100, 15, SecondaryEffects.RARE_FLINCH, "pokemon")
MAGMA_STORM = Move("Magma Storm", Type.FIRE, MoveCategory.SPECIAL, 100, 75, 5, SecondaryEffects.MAGMA_STORM, "pokemon")
SHADOW_BALL = Move("Shadow Ball", Type.GHOST, MoveCategory.SPECIAL, 80, 100, 15, SecondaryEffects.RARE_SPECIAL_DEFENSE_DOWN, "pokemon", bullet_move=True)
SLUDGE_BOMB = Move("Sludge Bomb", Type.POISON, MoveCategory.SPECIAL, 90, 100, 10, SecondaryEffects.COMMON_POISON, "pokemon", bullet_move=True)
SLUDGE_WAVE = Move("Sludge Wave", Type.POISON, MoveCategory.SPECIAL, 95, 100, 10, SecondaryEffects.COMMON_POISON, "pokemon")
HURRICANE = Move("Hurricane", Type.FLYING, MoveCategory.SPECIAL, 110, 70, 10, SecondaryEffects.COMMON_CONFUSION, "pokemon")
IRON_HEAD = Move("Iron Head", Type.STEEL, MoveCategory.PHYSICAL, 80, 100, 15, SecondaryEffects.COMMON_FLINCH, "pokemon")
ENERGY_BALL = Move("Energy Ball", Type.GRASS, MoveCategory.SPECIAL, 90, 100, 10, SecondaryEffects.RARE_SPECIAL_DEFENSE_DOWN, "pokemon", bullet_move=True)
BOOMBURST = Move("Boomburst", Type.NORMAL, MoveCategory.SPECIAL, 140, 100, 10, SecondaryEffects.NONE, "pokemon", sound_move=True)
POISON_JAB = Move("Poison Jab", Type.POISON, MoveCategory.PHYSICAL, 80, 100, 20, SecondaryEffects.COMMON_POISON, "pokemon")
LIQUIDADATION = Move("Liquidation", Type.WATER, MoveCategory.PHYSICAL, 85, 100, 10, SecondaryEffects.NONE, "pokemon")
LEAF_BLADE = Move("Leaf Blade", Type.GRASS, MoveCategory.PHYSICAL, 90, 100, 15, SecondaryEffects.NONE, "pokemon")
DRACO_METEOR = Move("Draco Meteor", Type.DRAGON, MoveCategory.SPECIAL, 130, 90, 5, SecondaryEffects.LOWER_SPE_ATK_BY_2, "pokemon")
DRAGON_PULSE = Move("Dragon Pulse", Type.DRAGON, MoveCategory.SPECIAL, 85, 100, 10, SecondaryEffects.NONE, "pokemon")
